services:

  postgres:
    image: postgres:latest
    container_name: postgres_belkin
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres_db
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d postgres_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  pgadmin:
    container_name: pgadmin_belkin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: email@mail.ru
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
      
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - DATABASE_URL=postgresql+asyncpg://root:root@postgres:5432/postgres_db
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    ports:
      - "8000:80"
    depends_on:
      - backend

    
  nginx:
    image: nginx:latest
    container_name: nginx_belkin
    ports:
      - "9090:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./frontend/dist:/usr/share/nginx/html:ro
    depends_on:
      - backend
      - frontend

volumes:
  pgdata:
  pgadmin-data: